### ISSUE TITLE
[FEATURE] Compatibility with TYPO3 CMS 7

### ISSUE THREAD

**Issue by hirnschmalz** [fabarea/media#13]
Hi,

are there any plans for a version working with TYPO3 CMS 7? Maybe I can help a little bit.

Markus

**Comment by fabarea** [comment]
It is in the pipeline but I haven't had the time to properly finish it. Currently if you install Vidi with CMS 7, you'll see the default modules below the User Settings (upper right corner) since the menu "User" was moved over there. Clicking on the FE User Vidi module gives some output but with some mistake. If you would dig what is wrong that would be of course nice.

**Comment by pniederlag** [comment]
Hello ,

as 7LTS is around the corner now, do you have any roadmap and/or estimate on the required effort for porting media to 7.X?

thx for your work,

best regards,
Peter

**Comment by fabarea** [comment]
Definitely. I will tackle this task middle of next week.
