### ISSUE TITLE
MediaFilePicker doesn't show in version 3.6.0

### ISSUE THREAD

**Issue by wegewerk-klr** [fabarea/media#76]
The User TSConfig option "options.vidi.enableMediaFilePicker" doesn't switch the default filepicker with the media filepicker for typo3 version 6.2.14.
this seems to be a v3.6.0 problem only, because in the earlier versions i worked.

**Comment by fabarea** [comment]
I have just doubled check in my end and it looks fine. Make sure to well reload the BE after applying the settings. If you have freshly updated Media, you could also make a `rm -rf typo3temp/*` to ensure a "fresh" state.

**Comment by fabarea** [comment]
I will be more precise in the documentation:

You can use the option `options.vidi.enableMediaFilePicker` to control the display of the File Picker of Media. Pay attention, this option is only taken into consideration **if** the File Picker is activated in the Extension Manager first. The File Picker is the popup displayed to connect a File with a content element (like image) or with other kind of records. The Core popup is however used by default for the purpose of the folder tree. In the Media popup, the folder tree will not be displayed because of iframe issue. As tip, use the recursive browsing in Media to retrieve all your files.
